title: luli6382
description: luli6382 public site
theme: just-the-docs

plugins:
  - jekyll-default-layout

url: https://luli6382.github.io

aux_links:
  Repo Link: https://github.com/luli6382/luli6382.github.io

color_scheme: dark

collections:
  staff_members:
    output: true